set clipboard+=unnamedplus
syntax enable
filetype plugin indent on

" Use English interface.
language message C

"---------------------------------------------------------------------------
" Search:
"
" Ignore the case of normal letters.
set ignorecase
" If the search pattern contains upper case characters, override ignorecase
" option.
set smartcase
" Enable incremental search.
set incsearch
" highlight search result
set hlsearch
" Searches wrap around the end of the file.
set wrapscan

noremap <ESC><ESC> :nohlsearch<CR><ESC>

" 行末の空白削除
autocmd BufWritePre * :%s/\s\+$//ge

set nu
