[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_if = 1
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_event = 'TextYankPost'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_add = '''
  nmap <silent> <C-u><C-p> :<C-u>Denite file_rec<CR>
  nmap <silent> <C-u><C-g> :<C-u>Denite grep<CR>
  nmap <silent> <C-u><C-u> :<C-u>Denite buffer file_mru<CR>
  nmap <silent> <C-u><C-y> :<C-u>Denite neoyank<CR>
  nnoremap <silent> / :<C-u>Denite line<CR>
  nnoremap <silent> * :<C-u>DeniteCursorWord line<CR>
'''
hook_source = '''
  source ~/.config/nvim/plugins/denite.vim
'''

[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = '''
  let g:memolist_denite = 1
'''
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = 'Deol'
hook_add = '''
  tnoremap <silent> <ESC> <C-\><C-n>
  tnoremap <C-w>h <C-><C-n><C-w>h
  tnoremap <C-w>j <C-><C-n><C-w>j
  tnoremap <C-w>k <C-><C-n><C-w>k
  tnoremap <C-w>l <C-><C-n><C-w>l
'''
